spring.application.name=stock-monitor-service
# DIFFERENT local port so they don't clash in your IDE
server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/spring_java_internship_stock_alert_db}
spring.datasource.username=postgres
spring.datasource.password=postgres

# Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=stock-monitor-group