spring.application.name=stock-monitor-service
server.port=8083

spring.config.import=optional:file:.env[.properties], optional:file:../.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5433/spring_java_internship_stock_alert_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=stock-monitor-group

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

finnhub.api.base-url=${FINNHUB_API_BASE_URL}
finnhub.api.key=${FINNHUB_API_KEY}