spring.application.name=stock-alert-service
server.port=8080

spring.config.import=optional:file:.env[.properties], optional:file:../.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5433/spring_java_internship_stock_alert_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.kafka.bootstrap-servers=localhost:9092

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.flyway.locations=classpath:db/migration
spring.jpa.hibernate.ddl-auto=none