spring.application.name=stock-alert-service
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/spring_java_internship_stock_alert_db}
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}